{
    "changed": false,
    "failed": true,
    "msg": "All items completed",
    "results": [
        {
            "ansible_loop_var": "item",
            "changed": false,
            "exception": "Traceback (most recent call last):\n  File \"/home/pk/.ansible/tmp/ansible-local-12021ocwobdvw/ansible-tmp-1591270040.6247234-26300139433248/AnsiballZ_napalm_validate.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/pk/.ansible/tmp/ansible-local-12021ocwobdvw/ansible-tmp-1591270040.6247234-26300139433248/AnsiballZ_napalm_validate.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/pk/.ansible/tmp/ansible-local-12021ocwobdvw/ansible-tmp-1591270040.6247234-26300139433248/AnsiballZ_napalm_validate.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib/python3.6/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_napalm_validate_payload_o36l3hgp/__main__.py\", line 260, in <module>\n  File \"/tmp/ansible_napalm_validate_payload_o36l3hgp/__main__.py\", line 239, in main\n  File \"/tmp/ansible_napalm_validate_payload_o36l3hgp/__main__.py\", line 139, in get_compliance_report\n  File \"/home/pk/.local/lib/python3.6/site-packages/napalm/base/base.py\", line 1676, in compliance_report\n    self, validation_file=validation_file, validation_source=validation_source\n  File \"/home/pk/.local/lib/python3.6/site-packages/napalm/base/validate.py\", line 200, in compliance_report\n    key = expected_results.pop(\"_name\", \"\") or getter\nAttributeError: 'NoneType' object has no attribute 'pop'\n",
            "failed": true,
            "item": "interfaces",
            "module_stderr": "Traceback (most recent call last):\n  File \"/home/pk/.ansible/tmp/ansible-local-12021ocwobdvw/ansible-tmp-1591270040.6247234-26300139433248/AnsiballZ_napalm_validate.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/pk/.ansible/tmp/ansible-local-12021ocwobdvw/ansible-tmp-1591270040.6247234-26300139433248/AnsiballZ_napalm_validate.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/pk/.ansible/tmp/ansible-local-12021ocwobdvw/ansible-tmp-1591270040.6247234-26300139433248/AnsiballZ_napalm_validate.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib/python3.6/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_napalm_validate_payload_o36l3hgp/__main__.py\", line 260, in <module>\n  File \"/tmp/ansible_napalm_validate_payload_o36l3hgp/__main__.py\", line 239, in main\n  File \"/tmp/ansible_napalm_validate_payload_o36l3hgp/__main__.py\", line 139, in get_compliance_report\n  File \"/home/pk/.local/lib/python3.6/site-packages/napalm/base/base.py\", line 1676, in compliance_report\n    self, validation_file=validation_file, validation_source=validation_source\n  File \"/home/pk/.local/lib/python3.6/site-packages/napalm/base/validate.py\", line 200, in compliance_report\n    key = expected_results.pop(\"_name\", \"\") or getter\nAttributeError: 'NoneType' object has no attribute 'pop'\n",
            "module_stdout": "",
            "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
            "rc": 1
        },
        {
            "ansible_loop_var": "item",
            "changed": false,
            "exception": "Traceback (most recent call last):\n  File \"/home/pk/.ansible/tmp/ansible-local-12021ocwobdvw/ansible-tmp-1591270049.1744053-150775377737425/AnsiballZ_napalm_validate.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/pk/.ansible/tmp/ansible-local-12021ocwobdvw/ansible-tmp-1591270049.1744053-150775377737425/AnsiballZ_napalm_validate.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/pk/.ansible/tmp/ansible-local-12021ocwobdvw/ansible-tmp-1591270049.1744053-150775377737425/AnsiballZ_napalm_validate.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib/python3.6/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_napalm_validate_payload_vw1ng567/__main__.py\", line 260, in <module>\n  File \"/tmp/ansible_napalm_validate_payload_vw1ng567/__main__.py\", line 239, in main\n  File \"/tmp/ansible_napalm_validate_payload_vw1ng567/__main__.py\", line 139, in get_compliance_report\n  File \"/home/pk/.local/lib/python3.6/site-packages/napalm/base/base.py\", line 1676, in compliance_report\n    self, validation_file=validation_file, validation_source=validation_source\n  File \"/home/pk/.local/lib/python3.6/site-packages/napalm/base/validate.py\", line 200, in compliance_report\n    key = expected_results.pop(\"_name\", \"\") or getter\nAttributeError: 'NoneType' object has no attribute 'pop'\n",
            "failed": true,
            "item": "bgp",
            "module_stderr": "Traceback (most recent call last):\n  File \"/home/pk/.ansible/tmp/ansible-local-12021ocwobdvw/ansible-tmp-1591270049.1744053-150775377737425/AnsiballZ_napalm_validate.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/pk/.ansible/tmp/ansible-local-12021ocwobdvw/ansible-tmp-1591270049.1744053-150775377737425/AnsiballZ_napalm_validate.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/pk/.ansible/tmp/ansible-local-12021ocwobdvw/ansible-tmp-1591270049.1744053-150775377737425/AnsiballZ_napalm_validate.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib/python3.6/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_napalm_validate_payload_vw1ng567/__main__.py\", line 260, in <module>\n  File \"/tmp/ansible_napalm_validate_payload_vw1ng567/__main__.py\", line 239, in main\n  File \"/tmp/ansible_napalm_validate_payload_vw1ng567/__main__.py\", line 139, in get_compliance_report\n  File \"/home/pk/.local/lib/python3.6/site-packages/napalm/base/base.py\", line 1676, in compliance_report\n    self, validation_file=validation_file, validation_source=validation_source\n  File \"/home/pk/.local/lib/python3.6/site-packages/napalm/base/validate.py\", line 200, in compliance_report\n    key = expected_results.pop(\"_name\", \"\") or getter\nAttributeError: 'NoneType' object has no attribute 'pop'\n",
            "module_stdout": "",
            "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
            "rc": 1
        }
    ]
}